// Copyright 2023 The CreeperCoding Authors. All rights reserved.
// SPDX-License-Identifier: MIT

package misc

import (
	"fmt"
	"net/http"
	"path"
	"strconv"
	"strings"

	"creepercoding.dev/modules/git"
	"creepercoding.dev/modules/httpcache"
	"creepercoding.dev/modules/httplib"
	"creepercoding.dev/modules/json"
	"creepercoding.dev/modules/log"
	"creepercoding.dev/modules/setting"
	"creepercoding.dev/modules/util"
	"creepercoding.dev/modules/web/middleware"
	"creepercoding.dev/services/context"
)

func SiteManifest(w http.ResponseWriter, req *http.Request) {
	w.Header().Set("Content-Type", "application/manifest+json")
	if httpcache.HandleGenericETagPublicCache(req, w, "", &setting.AppStartTime) {
		return
	}
	if req.Method == http.MethodHead {
		return
	}

	ctx := req.Context()
	absoluteAssetURL := strings.TrimSuffix(httplib.MakeAbsoluteURL(ctx, setting.StaticURLPrefix), "/")
	manifest := map[string]any{
		"name":       setting.AppName,
		"short_name": setting.AppName,
		"start_url":  httplib.GuessCurrentAppURL(ctx),
		"icons": []map[string]string{
			{"src": absoluteAssetURL + "/assets/img/logo.png", "type": "image/png", "sizes": "512x512"},
			{"src": absoluteAssetURL + "/assets/img/logo.svg", "type": "image/svg+xml", "sizes": "512x512"},
		},
	}
	_ = json.NewEncoder(w).Encode(manifest)
}

func SSHInfo(rw http.ResponseWriter, req *http.Request) {
	if !git.DefaultFeatures().SupportProcReceive {
		rw.WriteHeader(http.StatusNotFound)
		return
	}
	rw.Header().Set("content-type", "text/json;charset=UTF-8")
	_, err := rw.Write([]byte(`{"type":"agit","version":1}`))
	if err != nil {
		log.Error("fail to write result: err: %v", err)
		rw.WriteHeader(http.StatusInternalServerError)
		return
	}
	rw.WriteHeader(http.StatusOK)
}

func DummyOK(w http.ResponseWriter, req *http.Request) {
	w.WriteHeader(http.StatusOK)
}

func RobotsTxt(w http.ResponseWriter, req *http.Request) {
	robotsTxt := util.FilePathJoinAbs(setting.CustomPath, "public/robots.txt")
	if ok, _ := util.IsExist(robotsTxt); !ok {
		robotsTxt = util.FilePathJoinAbs(setting.CustomPath, "robots.txt") // the legacy "robots.txt"
	}
	httpcache.SetCacheControlInHeader(w.Header(), httpcache.CacheControlForPublicStatic())
	http.ServeFile(w, req, robotsTxt)
}

func StaticRedirect(target string) func(w http.ResponseWriter, req *http.Request) {
	return func(w http.ResponseWriter, req *http.Request) {
		http.Redirect(w, req, path.Join(setting.StaticURLPrefix, target), http.StatusMovedPermanently)
	}
}

func LocationRedirect(target string) func(w http.ResponseWriter, req *http.Request) {
	return func(w http.ResponseWriter, req *http.Request) {
		http.Redirect(w, req, target, http.StatusSeeOther)
	}
}

func WebBannerDismiss(ctx *context.Context) {
	_, rev, _ := setting.Config().Instance.WebBanner.ValueRevision(ctx)
	middleware.SetSiteCookie(ctx.Resp, middleware.CookieWebBannerDismissed, strconv.Itoa(rev), 48*3600)
	ctx.JSONOK()
}

func SkillMD(w http.ResponseWriter, req *http.Request) {
	w.Header().Set("Content-Type", "text/markdown; charset=utf-8")
	w.WriteHeader(http.StatusOK)
	content := fmt.Sprintf(`# SKILL.md – AI Agent Guide

This instance is **%s** — a CreeperCoding forge.

CreeperCoding is a fork of [Gitea](https://about.gitea.com/). Its REST API and Git protocol are fully compatible with Gitea, so any tool or AI agent that knows how to interact with a Gitea instance can work here without modification.

## Quick facts

| Attribute | Value |
|-----------|-------|
| Instance | %s |
| Fork of | Gitea |
| API base | %sapi/v1 |
| API docs | %sapi/swagger |

## Using the API

1. Authenticate via ` + "`Authorization: token YOUR_TOKEN`" + ` header (personal access tokens are managed under User Settings → Applications).
2. All standard Gitea API endpoints are available — issues, pull requests, repos, users, organisations, etc.
3. Refer to the [Gitea API reference](https://docs.gitea.com/api/1.20/) for endpoint details; the behaviour is identical.

## AI agent notes

- The built-in AI agent on this instance is **@ccopilot**. You can mention it in issue and PR comments.
- ` + "`@ccopilot`" + ` can review PRs, suggest commit messages, and create branches with proposed changes.
- Admin config for ccopilot is under Site Administration → Ccopilot Settings.
- Repository owners can disable ccopilot per-repo under Settings → Advanced → "Disable ccopilot bot".

---

*This page is auto-generated by the CreeperCoding instance.*
`, setting.AppName, setting.AppName, setting.AppURL, setting.AppURL)
	_, _ = fmt.Fprint(w, content)
}
